Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/DetailedInnoGotchiViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class DetailedInnoGotchiViewModel : InnoGotchiViewModelBase
{
    public DateTime LastFeedTime { get; set; }
    public DateTime LastDrinkTime { get; set; }
    public DateTime AgeUpdatedAt { get; set; }
    public DateTime LiveSince { get; set; }
    public DateTime DeadSince { get; set; }
    public int HappinessDaysCount { get; set; }
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/InnoGotchiActionViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class InnoGotchiActionViewModel
{
    public Guid InnoGotchiId { get; set; }
    public string ActionName { get; set; } = null!;
    public string ActionText { get; set; } = null!;
    public bool IsDisabled { get; set; }
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/InnoGotchiLinkViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class InnoGotchiLinkViewModel
{
    public string Description { get; set; } = null!;
    public int LinkSortType { get; set; }
    public int CurrentSortType { get; set; }
    public int PageSize { get; set; }
    public bool IsAscending { get; set; }
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/InnoGotchiRequestViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class InnoGotchiRequestViewModel
{
    public Guid Id { get; set; }
    public bool CanSeeDetails { get; set; }
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/InnoGotchiStatusViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class InnoGotchiStatusViewModel
{
    public string Status { get; init; } = null!;
    public string BadgeStyleClasses { get; init; } = null!;
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/InnoGotchiViewModelBase.cs
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Components;

namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class InnoGotchiViewModelBase
{
    public Guid Id { get; set; }
    public string Name { get; set; } = null!;
    public int Age { get; set; }
    public string HungerLevel { get; set; } = null!;
    public string ThirstyLevel { get; set; } = null!;
    public bool IsDead { get; set; }
    public bool IsFeedingAllowable { get; set; }
    public bool IsDrinkingAllowable { get; set; }
    public bool IsNewBorn { get; set; }
    public List<InnoGotchiComponentViewModel> Components { get; set; } = null!;
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/PreviewInnoGotchiViewModel.cs
namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class PreviewInnoGotchiViewModel : InnoGotchiViewModelBase
{
}

Client/PhlegmaticOne.InnoGotchi.Web/ViewModels/InnoGotchies/ReadonlyInnoGotchiPreviewViewModel.cs
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Components;

namespace PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;

public class ReadonlyInnoGotchiPreviewViewModel
{
    public Guid Id { get; set; }
    public string Name { get; set; } = null!;
    public int Age { get; set; }
    public string HungerLevel { get; set; } = null!;
    public string ThirstyLevel { get; set; } = null!;
    public bool IsDead { get; set; }
    public bool IsNewBorn { get; set; }
    public string ProfileFarmName { get; set; } = null!;
    public string ProfileFirstName { get; set; } = null!;
    public string ProfileLastName { get; set; } = null!;
    public List<InnoGotchiComponentViewModel> Components { get; set; } = null!;
}

Client/PhlegmaticOne.InnoGotchi.Web/Controllers/InnoGotchiesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhlegmaticOne.ApiRequesting.Services;
using PhlegmaticOne.InnoGotchi.Shared.InnoGotchies;
using PhlegmaticOne.InnoGotchi.Shared.PagedList;
using PhlegmaticOne.InnoGotchi.Web.Controllers.Base;
using PhlegmaticOne.InnoGotchi.Web.Requests.InnoGotchies;
using PhlegmaticOne.InnoGotchi.Web.ViewModels.InnoGotchies;
using PhlegmaticOne.LocalStorage;
using PhlegmaticOne.PagedLists.Implementation;

namespace PhlegmaticOne.InnoGotchi.Web.Controllers;

[Authorize]
public class InnoGotchiesController : ClientRequestsController
{
    public InnoGotchiesController(IClientRequestsService clientRequestsService,
        ILocalStorageService localStorageService, IMapper mapper) :
        base(clientRequestsService, localStorageService, mapper) { }

    [HttpGet]
    public Task<IActionResult> All(int? pageIndex, int? pageSize, int? sortType, bool? isAscending)
    {
        var pagedListData = new PagedListData
        {
            PageIndex = pageIndex is null ? 0 : pageIndex.Value - 1,
            PageSize = pageSize ?? 15,
            SortType = sortType ?? 0,
            IsAscending = isAscending ?? false
        };

        return FromAuthorizedGet(new GetInnoGotchiesPagedListRequest(pagedListData), list =>
        {
            ViewData["PageSize"] = pagedListData.PageSize;
            ViewData["SortType"] = pagedListData.SortType;
            ViewData["IsAscending"] = pagedListData.IsAscending;

            var mapped = Mapper.Map<PagedList<ReadonlyInnoGotchiPreviewViewModel>>(list);
            IActionResult view = View(mapped);
            return Task.FromResult(view);
        });
    }

    [HttpGet]
    public Task<IActionResult> Pet(Guid petId) => 
        FromAuthorizedGet(new GetDetailedInnoGotchiRequest(petId), InnoGotchiView);

    [HttpPost]
    public Task<IActionResult> Feed(InnoGotchiActionViewModel innoGotchiActionViewModel)
    {
        var model = FeedModel(innoGotchiActionViewModel.InnoGotchiId);
        return FromAuthorizedPut(new UpdateInnoGotchiRequest(model), _ =>
        {
            var getPetRequest = new GetDetailedInnoGotchiRequest(innoGotchiActionViewModel.InnoGotchiId);
            return FromAuthorizedGet(getPetRequest, InnoGotchiView);
        },
        onOperationFailed: result => ErrorView(result.ErrorMessage!));
    }

    [HttpPost]
    public Task<IActionResult> Drink(InnoGotchiActionViewModel innoGotchiActionViewModel)
    {
        var model = DrinkModel(innoGotchiActionViewModel.InnoGotchiId);
        return FromAuthorizedPut(new UpdateInnoGotchiRequest(model), _ =>
        {
            var getPetRequest = new GetDetailedInnoGotchiRequest(innoGotchiActionViewModel.InnoGotchiId);
            return FromAuthorizedGet(getPetRequest, InnoGotchiView);
        }, 
        onOperationFailed: result => ErrorView(result.ErrorMessage!));
    }

    [HttpPost]
    public Task<IActionResult> FeedPartial([FromBody] InnoGotchiRequestViewModel request)
    {
        var model = FeedModel(request.Id);
        return FromAuthorizedPut(new UpdateInnoGotchiRequest(model), _ =>
        {
            var getPetRequest = new GetPreviewInnoGotchiRequest(request.Id);
            return FromAuthorizedGet(getPetRequest, 
                dto => InnoGotchiCardPartialView(dto, request.CanSeeDetails));
        }, result => ErrorView(result.ErrorMessage!));
    }

    [HttpPost]
    public Task<IActionResult> DrinkPartial([FromBody] InnoGotchiRequestViewModel request)
    {
        var model = DrinkModel(request.Id);
        return FromAuthorizedPut(new UpdateInnoGotchiRequest(model), result =>
        {
            var getPetRequest = new GetPreviewInnoGotchiRequest(request.Id);
            return FromAuthorizedGet(getPetRequest, 
                dto => InnoGotchiCardPartialView(dto, request.CanSeeDetails));
        }, result => ErrorView(result.ErrorMessage!));
    }

    private Task<IActionResult> InnoGotchiView(DetailedInnoGotchiDto innoGotchi)
    {
        var result = Mapper.Map<DetailedInnoGotchiViewModel>(innoGotchi);
        IActionResult view = View(nameof(Pet), result);
        return Task.FromResult(view);
    }

    private Task<IActionResult> InnoGotchiCardPartialView(PreviewInnoGotchiDto innoGotchi, bool canSeeDetails)
    {
        ViewData["CanSeeDetails"] = canSeeDetails;
        var result = Mapper.Map<PreviewInnoGotchiViewModel>(innoGotchi);
        IActionResult view = PartialView("~/Views/_Partial_Views/InnoGotchies/InnoGotchiCard.cshtml", result);
        return Task.FromResult(view);
    }

    private static UpdateInnoGotchiDto FeedModel(Guid petId) =>
        new()
        {
            InnoGotchiOperationType = InnoGotchiOperationType.Feeding,
            PetId = petId
        };

    private static UpdateInnoGotchiDto DrinkModel(Guid petId) =>
        new()
        {
            InnoGotchiOperationType = InnoGotchiOperationType.Drinking,
            PetId = petId
        };
}

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiActionButton.cshtml
@model InnoGotchiActionViewModel

@if (Model.IsDisabled)
{
    <a href="#" class="btn btn-outline-light disabled">@Model.ActionText</a>
}
else
{
    <form method="post" asp-controller="InnoGotchies" asp-action="@Model.ActionName">
        <input hidden asp-for="InnoGotchiId"/>
        <button class="btn btn-outline-light btn-dark" type="submit">@Model.ActionText</button>
    </form>
}

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiCard.cshtml
@model PreviewInnoGotchiViewModel

@{
    var canSeeDetails = ViewData["CanSeeDetails"] as bool?;
}

<div class="row mt-4 ms-2 me-2 pet-card">
    <div style="height: 186px; width: 150px">
        @await Html.PartialAsync("~/Views/_Partial_Views/Shared/ImageFromComponents.cshtml", Model.Components)
    </div>
    <div class="card-body">
        <input class="pet_id" hidden asp-for="Id"/>
        <h4 class="card-title pt-1">@Model.Name</h4>
        <div>
            <label>Hunger level: <vc:inno-gotchi-status status="@Model.HungerLevel" /></label><br />
            <label>Thirsty level: <vc:inno-gotchi-status status="@Model.ThirstyLevel" /></label><br />
            <label>Age: @Model.Age</label><br/>
        </div>
        <div class="mt-3 body-links">
            <button class="btn btn-outline-secondary btn-dark feed_button @(TryDisableFeed())">Feed</button>
            <button class="btn btn-outline-secondary btn-dark drink_button @(TryDisableDrink())">Drink</button>

            @if (canSeeDetails is true)
            {
                <a asp-controller="InnoGotchies" asp-action="Pet" asp-route-petId="@Model.Id"
                   class="btn btn-outline-secondary btn-dark">
                    Details
                </a>
            }
        </div>
    </div>
</div>

@functions
{
    string TryDisableFeed()
    {
        return Model.IsFeedingAllowable == false ? "disabled" : string.Empty;
    }

    string TryDisableDrink()
    {
        return Model.IsDrinkingAllowable == false ? "disabled" : string.Empty;
    }
}

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiCardsList.cshtml
@model IEnumerable<PreviewInnoGotchiViewModel>

<div class="card-group vgr-cards mt-2 justify-content-around">
    <input hidden value="@(ViewData["CanSeeDetails"]!.ToString()!.ToLower())" id="can-see-details"/>
    @foreach (var innoGotchi in Model)
    {
        <div>
            @await Html.PartialAsync("~/Views/_Partial_Views/InnoGotchies/InnoGotchiCard.cshtml", innoGotchi, ViewData)
        </div>
    }
</div>

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiSortLink.cshtml
@model InnoGotchiLinkViewModel

<a class="btn btn-dark btn-outline-light"
   asp-controller="InnoGotchies"
   asp-action="All"
   asp-route-pageIndex="1"
   asp-route-pageSize="@Model.PageSize"
   asp-route-sortType="@Model.LinkSortType"
   asp-route-isAscending="@(Model.CurrentSortType == Model.LinkSortType && Model.IsAscending == false)">
    @Model.Description
</a>

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiStatus.cshtml
@model InnoGotchiStatusViewModel

<span class="badge @Model.BadgeStyleClasses">
    @Model.Status
</span>

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/InnoGotchiesSortMenu.cshtml
@model List<string>
@{
    var isAscending = (bool)ViewData["IsAscending"]!;
    var sortType = (int)ViewData["SortType"]!;
    var pageSize = (int)ViewData["PageSize"]!;
}

<h3 class="text-white text-center">InnoGotchies sort menu</h3>

<div class="btn-group mt-2" role="group">
    @for (var i = 0; i < Model.Count; i++)
    {
        @await Html.PartialAsync("~/Views/_Partial_Views/InnoGotchies/InnoGotchiSortLink.cshtml", new InnoGotchiLinkViewModel
        {
            IsAscending = isAscending,
            LinkSortType = i,
            PageSize = pageSize,
            CurrentSortType = sortType,
            Description = Model[i]
        })
    }
</div>

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/ReadonlyInnoGotchi.cshtml
@model ReadonlyInnoGotchiPreviewViewModel

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-2 col-md-4 col-sm-6 col-6">
            @await Html.PartialAsync("~/Views/_Partial_Views/Shared/ImageFromComponents.cshtml", Model.Components)
        </div>

        <div class="col-lg-10 col-md-8 col-sm-6 col-6 pet-info text-dark" style="background: wheat !important; border-radius: 0.7rem">
            <div class="row">
                @if (Model.IsNewBorn)
                {
                    <h4 class="h4 text-center">Name: @(Model.Name).<vc:inno-gotchi-status status="newborn" /></h4>
                }
                else if (Model.IsDead)
                {
                    <h4 class="h4 text-center">Name: @(Model.Name). <vc:inno-gotchi-status status="dead" /></h4>
                }
                else
                {
                    <h4 class="h4 text-center">Name: @(Model.Name). <vc:inno-gotchi-status status="alive"/></h4>
                }
            </div>

            <div class="row">
                <div class="col-md-6">
                    <h4 class="my-3 h4">Vital signs</h4>

                    <h6 class="h6">Hunger level: <vc:inno-gotchi-status status="@Model.HungerLevel" /></h6>
                    <h6 class="h6">Thirsty level: <vc:inno-gotchi-status status="@Model.ThirstyLevel" /></h6>
                    <h6 class="h6">Age: @Model.Age</h6>
                </div>
                <div class="col-md-6">
                    <h4 class="my-3 h4">Owner's information</h4>

                    <h6 class="h6">First name: @Model.ProfileFirstName</h6>
                    <h6 class="h6">Last name: @Model.ProfileLastName</h6>
                    <h6 class="h6">Farm name: @Model.ProfileFarmName</h6>
                </div>
            </div>
        </div>
    </div>
</div>

Client/PhlegmaticOne.InnoGotchi.Web/Views/_Partial_Views/InnoGotchies/ReadonlyInnoGotchiesCollection.cshtml
@model IList<ReadonlyInnoGotchiPreviewViewModel>

@foreach (var model in Model)
{
    @await Html.PartialAsync("~/Views/_Partial_Views/InnoGotchies/ReadOnlyInnoGotchi.cshtml", model)
}