Client/PhlegmaticOne.InnoGotchi.Web/Controllers/AuthController.cs
using AutoMapper;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhlegmaticOne.ApiRequesting.Services;
using PhlegmaticOne.InnoGotchi.Shared.Profiles.Anonymous;
using PhlegmaticOne.InnoGotchi.Web.Controllers.Base;
using PhlegmaticOne.InnoGotchi.Web.Requests.Profile;
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Account;
using PhlegmaticOne.LocalStorage;

namespace PhlegmaticOne.InnoGotchi.Web.Controllers;

[AllowAnonymous]
public class AuthController : ClientRequestsController
{
    private readonly IValidator<RegisterViewModel> _registerViewModelValidator;

    public AuthController(IClientRequestsService clientRequestsService,
        ILocalStorageService localStorageService,
        IValidator<RegisterViewModel> registerViewModelValidator,
        IMapper mapper) :
        base(clientRequestsService, localStorageService, mapper)
    {
        _registerViewModelValidator = registerViewModelValidator;
    }

    [HttpGet]
    public IActionResult Login(string returnUrl) => View();

    [HttpGet]
    public IActionResult Register() => View();

    [HttpPost]
    public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
    {
        var validationResult = await _registerViewModelValidator.ValidateAsync(registerViewModel);

        if (validationResult.IsValid == false)
        {
            return ViewWithErrorsFromValidationResult(validationResult, nameof(Register), registerViewModel);
        }

        var registerDto = Mapper.Map<RegisterProfileDto>(registerViewModel);

        return await FromAuthorizedPost(new RegisterProfileRequest(registerDto), async profile =>
        {
            await AuthenticateAsync(profile);
            return RedirectToAction("Details", "Profile");
        }, result => ViewWithErrorsFromOperationResult(result, nameof(Register), registerViewModel));
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginViewModel loginViewModel)
    {
        var loginDto = Mapper.Map<LoginDto>(loginViewModel);

        return await FromAuthorizedPost(new LoginProfileRequest(loginDto), async profile =>
        {
            await AuthenticateAsync(profile);
            return loginViewModel.ReturnUrl is null
                ? RedirectToAction("Details", "Profile")
                : LocalRedirect(loginViewModel.ReturnUrl);
        }, result => ViewWithErrorsFromOperationResult(result, nameof(Login), loginViewModel));
    }
}

Client/PhlegmaticOne.InnoGotchi.Web/Controllers/AvatarController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PhlegmaticOne.ApiRequesting.Services;
using PhlegmaticOne.InnoGotchi.Web.Controllers.Base;
using PhlegmaticOne.InnoGotchi.Web.Requests.Profile;
using PhlegmaticOne.LocalStorage;

namespace PhlegmaticOne.InnoGotchi.Web.Controllers;

public class AvatarController : ClientRequestsController
{
    public AvatarController(IClientRequestsService clientRequestsService,
        ILocalStorageService localStorageService,
        IMapper mapper) :
        base(clientRequestsService, localStorageService, mapper) { }

    [HttpGet]
    public Task<IActionResult> Get()
    {
        return FromAuthorizedGet(new GetAvatarRequest(), avatarData =>
        {
            IActionResult result = File(avatarData, "image/png", "image.png");
            return Task.FromResult(result);
        });
    }
}

Client/PhlegmaticOne.InnoGotchi.Web/Controllers/FarmController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhlegmaticOne.ApiRequesting.Services;
using PhlegmaticOne.InnoGotchi.Shared.Farms;
using PhlegmaticOne.InnoGotchi.Web.Controllers.Base;
using PhlegmaticOne.InnoGotchi.Web.Requests.Farms;
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Farms;
using PhlegmaticOne.LocalStorage;

namespace PhlegmaticOne.InnoGotchi.Web.Controllers;

[Authorize]
public class FarmController : ClientRequestsController
{
    public FarmController(IClientRequestsService clientRequestsService,
        ILocalStorageService localStorageService, IMapper mapper) :
        base(clientRequestsService, localStorageService, mapper) { }

    [HttpGet]
    public IActionResult Create() => View();

    [HttpGet]
    public Task<IActionResult> My()
    {
        return FromAuthorizedGet(new GetDetailedFarmRequest(), farm =>
        {
            var farmViewModel = Mapper.Map<DetailedFarmViewModel>(farm);

            ViewData["CanSeeDetails"] = true;
            IActionResult view = View(farmViewModel);
            return Task.FromResult(view);
        }, failedResult =>
            ViewWithErrorsFromOperationResult(failedResult, nameof(Create), new CreateFarmViewModel()));
    }

    [HttpGet]
    public Task<IActionResult> Collaborated()
    {
        return FromAuthorizedGet(new GetCollaboratedFarmsRequest(), dtos =>
        {
            var viewModels = Mapper.Map<IList<PreviewFarmViewModel>>(dtos);
            IActionResult view = View(viewModels);
            return Task.FromResult(view);
        });
    }

    [HttpGet]
    public Task<IActionResult> View(Guid farmId)
    {
        return FromAuthorizedGet(new GetFarmRequest(farmId), dto =>
        {
            var mapped = Mapper.Map<DetailedFarmViewModel>(dto);
            ViewData["CanSeeDetails"] = false;
            IActionResult view = View(mapped);
            return Task.FromResult(view);
        });
    }

    [HttpPost]
    public Task<IActionResult> Create(CreateFarmViewModel createFarmViewModel)
    {
        var createFarmDto = Mapper.Map<CreateFarmDto>(createFarmViewModel);

        return FromAuthorizedPost(new CreateFarmRequest(createFarmDto), _ =>
        {
            IActionResult view = RedirectToAction(nameof(My));
            return Task.FromResult(view);
        }, result => ViewWithErrorsFromOperationResult(result, nameof(Create), createFarmViewModel));
    }
}

Client/PhlegmaticOne.InnoGotchi.Web/Controllers/OverviewController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhlegmaticOne.ApiRequesting.Services;
using PhlegmaticOne.InnoGotchi.Shared.ErrorMessages;
using PhlegmaticOne.InnoGotchi.Web.Controllers.Base;
using PhlegmaticOne.InnoGotchi.Web.Requests.Farms;
using PhlegmaticOne.InnoGotchi.Web.Requests.Overviews;
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Farms;
using PhlegmaticOne.InnoGotchi.Web.ViewModels.Statistics;
using PhlegmaticOne.LocalStorage;

namespace PhlegmaticOne.InnoGotchi.Web.Controllers;

[Authorize]
public class OverviewController : ClientRequestsController
{
    public OverviewController(IClientRequestsService clientRequestsService,
        ILocalStorageService localStorageService, IMapper mapper) :
        base(clientRequestsService, localStorageService, mapper) { }

    [HttpGet]
    public Task<IActionResult> My()
    {
        return FromAuthorizedGet(new GetIsFarmExistsRequest(), exists =>
        {
            IActionResult result = exists
                ? View()
                : View("~/Views/Farm/Create.cshtml", new CreateFarmViewModel
                {
                    ErrorMessage = AppErrorMessages.FarmDoesNotExistMessage
                });
            return Task.FromResult(result);
        });
    }

    [HttpGet]
    public Task<IActionResult> Collaborated()
    {
        return FromAuthorizedGet(new GetCollaboratedFarmStatisticsRequest(), statistics =>
        {
            var mapped = Mapper.Map<IList<PreviewFarmStatisticsViewModel>>(statistics);
            IActionResult view = View(mapped);
            return Task.FromResult(view);
        });
    }

    [HttpGet]
    public Task<IActionResult> MyPreviewPartial()
    {
        return FromAuthorizedGet(new GetPreviewFarmStatisticsRequest(), statistics =>
        {
            var viewModel = Mapper.Map<PreviewFarmStatisticsViewModel>(statistics);
            IActionResult view = PartialView("~/Views/_Partial_Views/Overview/PreviewFarmStatistics.cshtml", viewModel);
            return Task.FromResult(view);
        });
    }

    [HttpGet]
    public Task<IActionResult> MyDetailedPartial()
    {
        return FromAuthorizedGet(new GetDetailedFarmStatisticsRequest(), statistics =>
        {
            var viewModel = Mapper.Map<DetailedFarmStatisticsViewModel>(statistics);
            IActionResult view = PartialView("~/Views/_Partial_Views/Overview/DetailedFarmStatistics.cshtml",
                viewModel);
            return Task.FromResult(view);
        });
    }
}

Client/PhlegmaticOne.InnoGotchi.Web/Views/Shared/_Column_Layout.cshtml
@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-lg-9">
        @RenderBody()
    </div>
    <div class="col-lg-3">
        @await RenderSectionAsync("ColumnContent")
    </div>
</div>

@section Scripts
{
    @await RenderSectionAsync("Scripts", false)
}

@section Styles
{
    @await RenderSectionAsync("Styles", false)
}

Client/PhlegmaticOne.InnoGotchi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - InnoGotchi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PhlegmaticOne.InnoGotchi.Web.styles.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">InnoGotchi</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Constructor" asp-action="Create">Constructor</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Farm" asp-action="My">My farm</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Farm" asp-action="Collaborated">Collaborated farms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Overview" asp-action="My">Farms overview</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="InnoGotchies" asp-action="All">InnoGotchies</a>
                    </li>
                </ul>
                <div class="d-flex align-items-center">
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <div class="me-2">
                            <span class="text-white-50">@User.Identity.Name</span>
                        </div>
                        <div class="dropdown">
                            <button class="btn btn-dark dropdown-toggle" href="#"
                                    id="navbarDropdownMenuLink"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false">
                                <img class="rounded-circle"
                                     src="@Url.Action("Get", "Avatar")"
                                     height="40"
                                     asp-append-version="true"
                                     alt="Avatar"/>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Profile" asp-action="Details">Details</a>
                                <a class="dropdown-item" asp-controller="Profile" asp-action="Update">Settings</a>
                                <a class="dropdown-item" asp-controller="Profile" asp-action="Logout">Logout</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="btn-group" role="group">
                            <button class="btn btn-dark" onclick="location.href = '@Url.Action("Login", "Auth")'">
                                Login
                            </button>
                            <button class="btn btn-dark" onclick="location.href = '@Url.Action("Register", "Auth")'">
                                Register
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container">
        &copy; 2022 - PhlegmaticOne
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/layout.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>